version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  # Default linters (errcheck, govet, ineffassign, staticcheck, unused) are enabled automatically
  enable:
    - misspell
    - unconvert
    - unparam
    - gosec
    - bodyclose
    - noctx
    - prealloc
    - revive

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true

    govet:
      enable-all: true
      disable:
        - fieldalignment

    misspell:
      locale: US

    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unreachable-code

    gosec:
      excludes:
        - G104

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
          - unparam
          - errcheck

      - text: 'shadow: declaration of "err"'
        linters:
          - govet

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    gofmt:
      simplify: true

    goimports:
      local-prefixes:
        - github.com/pavlenkoa/vault-secrets-generator

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
