version: 2

project_name: vsg

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: vsg
    main: .
    binary: vsg
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/pavlenkoa/vault-secrets-generator/internal/command.Version={{.Version}}
      - -X github.com/pavlenkoa/vault-secrets-generator/internal/command.Commit={{.Commit}}
      - -X github.com/pavlenkoa/vault-secrets-generator/internal/command.BuildDate={{.Date}}

archives:
  - id: default
    ids:
      - vsg
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE
      - examples/*

brews:
  - name: vsg
    repository:
      owner: pavlenkoa
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/pavlenkoa/vault-secrets-generator"
    description: "Vault Secrets Generator - CLI tool for managing secrets in HashiCorp Vault"
    license: "Apache-2.0"
    test: |
      system "#{bin}/vsg", "version"

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: git
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - "(?i)^.*planned feature.*$"
      - "(?i)^.*implementation plan.*$"
      - Merge pull request
      - Merge branch
  groups:
    - title: "⚠️ Breaking Changes"
      regexp: "(?i)^.*breaking.*$"
      order: 0
    - title: Features
      regexp: "(?i)^.*(feat|implement|add(?!.*plan)).*$"
      order: 1
    - title: Bug Fixes
      regexp: "(?i)^.*(fix|bugfix).*$"
      order: 2
    - title: Infrastructure
      regexp: "(?i)^.*(update.*version|update.*depend|upgrade).*$"
      order: 3
    - title: Documentation
      regexp: "(?i)^.*(document|readme|claude\\.md).*$"
      order: 4
    - title: Other
      order: 999

release:
  github:
    owner: pavlenkoa
    name: vault-secrets-generator
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## VSG {{ .Version }}

    Vault Secrets Generator - A lightweight CLI tool for managing secrets in HashiCorp Vault.
  footer: |
    ## Docker

    ```bash
    docker pull ghcr.io/pavlenkoa/vault-secrets-generator:{{ .Version }}
    ```

    ## Installation

    ### Homebrew (macOS/Linux)
    ```bash
    brew install pavlenkoa/tap/vsg
    ```

    ### Binary
    Download the appropriate binary for your platform from the assets below.

dockers_v2:
  - id: default
    ids:
      - vsg
    dockerfile: Dockerfile.goreleaser
    images:
      - "ghcr.io/pavlenkoa/vault-secrets-generator"
    tags:
      - "{{ .Version }}"
      - "latest"
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.description": "Vault Secrets Generator"
      "org.opencontainers.image.url": "https://github.com/pavlenkoa/vault-secrets-generator"
      "org.opencontainers.image.source": "https://github.com/pavlenkoa/vault-secrets-generator"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.created": "{{ .Date }}"
