name: Lint & Test

on:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - 'go.*'
      - '.golangci.yaml'
      - '.github/workflows/lint.yaml'
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      go: ${{ steps.filter.outputs.go }}
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4
        id: filter
        with:
          filters: |
            go:
              - '**.go'
              - 'go.*'
              - '.golangci.yaml'
              - '.github/workflows/lint.yaml'

  lint:
    name: Lint & Test
    needs: changes
    if: needs.changes.outputs.go == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: "1.26"

      - name: Lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9
        with:
          version: v2.12.2

      - name: Test
        run: go test -v -race -coverprofile=coverage.out -covermode=atomic ./...

      - name: Build
        run: go build .
